services:
  nginx:
    container_name: nginx
    image: khr136/nginx:${NGINX_VERSION}
    restart: always
    ports:
      - "8080:80"
    networks:
      - docker-network

networks:
  docker-network:
    external: True
    name: ${DOCKER_NETWORK_NAME}
