---
- name: Install Docker and Docker Compose
  hosts: SERVER_1
  become: true
  roles:
    - docker

- name: Clone GitHub repository
  hosts: SERVER_1
  become: true
  roles:
    - github

- name: Deploy Docker container
  hosts: SERVER_1
  become: true
  roles:
    - deploy
