---
- name: Ensure git is installed
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true

- name: Ensure directory exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/app"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Clone GitHub repository
  ansible.builtin.git:
    repo: "{{ github_repo_url }}"
    dest: "/home/{{ ansible_user }}/app"
    version: main
    update: true
    force: true
  become: true
  become_user: "{{ ansible_user }}"
